export type DestinationData = Record<string, Record<string, string[]>>;

export const DESTINATION_DATA: DestinationData = {
  Europe: {
    France: ["Paris", "Nice", "Lyon", "Bordeaux", "Marseille", "Strasbourg", "Cannes", "Mont Saint-Michel"],
    Italy: ["Rome", "Milan", "Florence", "Venice", "Naples", "Amalfi Coast", "Cinque Terre", "Sicily", "Sardinia", "Turin"],
    Spain: ["Barcelona", "Madrid", "Seville", "Valencia", "Ibiza", "Mallorca", "Granada", "San Sebastián", "Tenerife"],
    Greece: ["Athens", "Santorini", "Mykonos", "Thessaloniki", "Crete", "Rhodes", "Corfu", "Zakynthos"],
    Portugal: ["Lisbon", "Porto", "Algarve", "Sintra", "Madeira", "Azores", "Coimbra"],
    Turkey: ["Istanbul", "Cappadocia", "Antalya", "Bodrum", "Izmir", "Pamukkale", "Trabzon"],
    "United Kingdom": ["London", "Edinburgh", "Manchester", "Oxford", "Cambridge", "Bath", "Liverpool", "Bristol", "Scottish Highlands"],
    Ireland: ["Dublin", "Galway", "Cork", "Killarney", "Cliffs of Moher", "Ring of Kerry"],
    Croatia: ["Dubrovnik", "Split", "Hvar", "Zagreb", "Pula", "Rovinj", "Plitvice Lakes"],
    Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Delft", "Maastricht"],
    Germany: ["Berlin", "Munich", "Hamburg", "Cologne", "Frankfurt", "Dresden", "Heidelberg", "Neuschwanstein"],
    Switzerland: ["Zurich", "Geneva", "Bern", "Interlaken", "Lucerne", "Zermatt", "St. Moritz"],
    Austria: ["Vienna", "Salzburg", "Innsbruck", "Hallstatt", "Graz"],
    Iceland: ["Reykjavik", "Golden Circle", "South Coast", "Westfjords", "Akureyri"],
    Norway: ["Oslo", "Bergen", "Fjords", "Tromsø", "Lofoten Islands", "Stavanger"],
    Sweden: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Lapland"],
    Denmark: ["Copenhagen", "Aarhus", "Odense", "Bornholm"],
    Finland: ["Helsinki", "Rovaniemi", "Turku", "Lapland", "Tampere"],
    Poland: ["Warsaw", "Kraków", "Gdańsk", "Wrocław", "Zakopane"],
    "Czech Republic": ["Prague", "Brno", "Český Krumlov", "Karlovy Vary"],
    Hungary: ["Budapest", "Eger", "Pécs", "Debrecen", "Lake Balaton"],
    Romania: ["Bucharest", "Transylvania", "Cluj-Napoca", "Brașov", "Sinaia"],
    Belgium: ["Brussels", "Bruges", "Ghent", "Antwerp", "Liège"],
    Malta: ["Valletta", "Mdina", "Gozo", "St. Julian's"],
    Cyprus: ["Nicosia", "Limassol", "Paphos", "Ayia Napa"],
    Scotland: ["Edinburgh", "Glasgow", "Highlands", "Isle of Skye", "Loch Ness"],
  },
  Asia: {
    Japan: ["Tokyo", "Kyoto", "Osaka", "Hiroshima", "Hokkaido", "Nara", "Nikkō", "Hakone"],
    Thailand: ["Bangkok", "Chiang Mai", "Phuket", "Koh Samui", "Krabi", "Koh Phangan", "Pai"],
    Indonesia: ["Bali", "Jakarta", "Yogyakarta", "Lombok", "Komodo", "Raja Ampat", "Sumatra"],
    UAE: ["Dubai", "Abu Dhabi", "Sharjah", "Fujairah"],
    Vietnam: ["Hanoi", "Ho Chi Minh City", "Ha Long Bay", "Hoi An", "Da Nang", "Nha Trang", "Sapa"],
    "South Korea": ["Seoul", "Busan", "Jeju Island", "Gyeongju", "Incheon"],
    India: ["Mumbai", "Delhi", "Jaipur", "Goa", "Kerala", "Agra", "Varanasi", "Rajasthan", "Darjeeling"],
    China: ["Beijing", "Shanghai", "Xi'an", "Chengdu", "Guilin", "Hangzhou", "Zhangjiajie"],
    Singapore: ["Marina Bay", "Sentosa", "Orchard Road", "Chinatown", "Little India"],
    Malaysia: ["Kuala Lumpur", "Penang", "Langkawi", "Borneo", "Cameron Highlands", "Melaka"],
    Philippines: ["Manila", "Cebu", "Palawan", "Boracay", "Siargao", "Davao"],
    Cambodia: ["Siem Reap", "Phnom Penh", "Sihanoukville", "Battambang"],
    Maldives: ["Malé Atoll", "Ari Atoll", "Baa Atoll", "North Malé Atoll"],
    "Sri Lanka": ["Colombo", "Sigiriya", "Kandy", "Galle", "Ella", "Trincomalee"],
    Nepal: ["Kathmandu", "Pokhara", "Everest Base Camp", "Chitwan", "Annapurna"],
    Jordan: ["Amman", "Petra", "Wadi Rum", "Aqaba", "Dead Sea"],
    Israel: ["Tel Aviv", "Jerusalem", "Eilat", "Haifa", "Nazareth"],
    Georgia: ["Tbilisi", "Batumi", "Kazbegi", "Kutaisi"],
    Oman: ["Muscat", "Nizwa", "Salalah", "Wahiba Sands"],
    Taiwan: ["Taipei", "Tainan", "Taroko Gorge", "Sun Moon Lake", "Kaohsiung"],
    Myanmar: ["Yangon", "Bagan", "Inle Lake", "Mandalay"],
  },
  Americas: {
    USA: ["New York", "Los Angeles", "Miami", "Las Vegas", "Hawaii", "San Francisco", "Chicago", "New Orleans", "Nashville", "Boston", "Washington D.C.", "Yellowstone"],
    Mexico: ["Cancún", "Mexico City", "Tulum", "Los Cabos", "Oaxaca", "Playa del Carmen", "Mérida", "Puerto Vallarta", "Guadalajara"],
    Brazil: ["Rio de Janeiro", "São Paulo", "Salvador", "Florianópolis", "Amazon", "Iguazu Falls", "Fortaleza", "Recife"],
    Colombia: ["Cartagena", "Medellín", "Bogotá", "Santa Marta", "Coffee Region", "Tayrona"],
    Argentina: ["Buenos Aires", "Patagonia", "Mendoza", "Bariloche", "Iguazu Falls", "Salta", "Ushuaia"],
    Peru: ["Lima", "Cusco", "Machu Picchu", "Sacred Valley", "Lake Titicaca", "Amazon", "Arequipa"],
    Chile: ["Santiago", "Patagonia", "Atacama Desert", "Easter Island", "Valparaíso", "Torres del Paine"],
    Ecuador: ["Quito", "Galápagos Islands", "Cuenca", "Amazon", "Otavalo"],
    Bolivia: ["La Paz", "Uyuni Salt Flats", "Sucre", "Potosí", "Lake Titicaca"],
    "Costa Rica": ["San José", "Manuel Antonio", "La Fortuna", "Monteverde", "Tortuguero", "Nicoya"],
    Canada: ["Toronto", "Vancouver", "Montreal", "Banff", "Quebec City", "Niagara Falls", "Whistler", "Prince Edward Island"],
    Cuba: ["Havana", "Varadero", "Trinidad", "Viñales", "Santiago de Cuba"],
    "Dominican Republic": ["Punta Cana", "Santo Domingo", "Samaná", "Puerto Plata", "La Romana"],
    Jamaica: ["Kingston", "Montego Bay", "Negril", "Ocho Rios"],
    Panama: ["Panama City", "Bocas del Toro", "Boquete", "San Blas Islands"],
    Uruguay: ["Montevideo", "Punta del Este", "Colonia del Sacramento"],
  },
  Africa: {
    Morocco: ["Marrakech", "Fez", "Casablanca", "Essaouira", "Chefchaouen", "Merzouga", "Rabat"],
    Kenya: ["Nairobi", "Mombasa", "Maasai Mara", "Amboseli", "Diani Beach", "Lake Nakuru"],
    "South Africa": ["Cape Town", "Johannesburg", "Kruger National Park", "Durban", "Garden Route", "Stellenbosch", "Knysna"],
    Egypt: ["Cairo", "Luxor", "Hurghada", "Sharm el-Sheikh", "Aswan", "Alexandria", "Sinai"],
    Tanzania: ["Dar es Salaam", "Zanzibar", "Serengeti", "Ngorongoro", "Kilimanjaro", "Arusha"],
    Tunisia: ["Tunis", "Sousse", "Djerba", "Hammamet", "Kairouan", "Tozeur"],
    Ethiopia: ["Addis Ababa", "Lalibela", "Danakil Depression", "Simien Mountains", "Axum"],
    Seychelles: ["Mahé", "Praslin", "La Digue", "Silhouette Island"],
    Mauritius: ["Port Louis", "Grand Baie", "Flic en Flac", "Île aux Cerfs"],
    Namibia: ["Windhoek", "Etosha National Park", "Sossusvlei", "Swakopmund", "Fish River Canyon"],
    Madagascar: ["Antananarivo", "Avenue of the Baobabs", "Nosy Be", "Isalo National Park"],
    Rwanda: ["Kigali", "Volcanoes National Park", "Nyungwe Forest", "Lake Kivu"],
    Ghana: ["Accra", "Cape Coast", "Kumasi", "Kakum National Park"],
    Senegal: ["Dakar", "Saint-Louis", "Casamance", "Saly", "Goree Island"],
    Zimbabwe: ["Harare", "Victoria Falls", "Hwange National Park", "Matobo Hills"],
  },
  Oceania: {
    Australia: ["Sydney", "Melbourne", "Brisbane", "Cairns", "Perth", "Gold Coast", "Uluru", "Great Barrier Reef", "Tasmania", "Adelaide"],
    "New Zealand": ["Auckland", "Queenstown", "Wellington", "Christchurch", "Rotorua", "Fiordland", "Bay of Islands"],
    Fiji: ["Nadi", "Suva", "Mamanuca Islands", "Yasawa Islands", "Coral Coast"],
    "French Polynesia": ["Tahiti", "Bora Bora", "Moorea", "Rangiroa", "Fakarava"],
    Vanuatu: ["Port Vila", "Espiritu Santo", "Tanna", "Champagne Beach"],
    Samoa: ["Apia", "Upolu", "Savai'i", "To Sua Ocean Trench"],
    "Papua New Guinea": ["Port Moresby", "Kokoda Track", "Sepik River", "Highlands"],
  },
};
