import asyncio
import json
from typing import Optional

from utils.parsers import Attraction
from prompts.attraction_prompt import build_attraction_prompt, build_rescore_prompt
from utils.llm import async_client, MODEL_HAIKU

from agents.sub_agents.restaurants import fetch_restaurants
from agents.sub_agents.nightlife import fetch_nightlife
from agents.sub_agents.history import fetch_history
from agents.sub_agents.sports import fetch_sports
from agents.sub_agents.extreme import fetch_extreme
from agents.sub_agents.treks import fetch_treks
from agents.sub_agents.beach import fetch_beach
from agents.sub_agents.spa import fetch_spa
from agents.sub_agents.events import fetch_events
from agents.sub_agents.shopping import fetch_shopping
from agents.sub_agents.generic import fetch_generic

from langsmith import traceable

client = async_client

@traceable(name="Attraction Manager", tags=["manager", "attraction"])
async def run_attraction_manager(
    input_data: dict,
    previous_output: Optional[list[dict]] = None,
    user_prompt: Optional[str] = None
) -> list[dict]:
    """
    Manages the fetching, filtering, and scoring of attractions across various sub-agents.

    Input Expectations:
    -------------------
    `input_data` must be a dictionary strictly adhering to this JSON schema:
    {
      "userName": "Alex Smith",
      "groupRelation": "family",
      "groupStructure": {
        "1": {"gender": "male", "age": 42}, ...
      },
      "budget": 2,
      "dates": {"start": "YYYY-MM-DD", "end": "YYYY-MM-DD"},
      "daysNumber": 5,
      "location": {"country": "France", "city": "Paris"},
      "accessibility": false,
      "interests": ["history", "shopping", "nightlife"]
    }

    `previous_output` is optional. If provided alongside `user_prompt`, it should be
    the exact output previously generated by this manager.
    
    `user_prompt` is optional. If provided alongside `previous_output`, the manager 
    will not fetch new data, but will instead use an LLM to refine and rescore the
    `previous_output` based on the user's feedback.

    Output Expectations:
    --------------------
    Returns a list of dictionaries. Each dictionary represents a category/type
    and contains a list of refined attraction results. The schema strictly matches:
    [
      {
        "type": "history",
        "results": [
          {
            "name": "Musée de l'Armée",
            "address": "129 Rue de Grenelle",
            ...
            "ageRange": "All ages",
            "subAgentScore": 9.5,
            "scoresLog": [9.5]
          }
        ]
      }
    ]
    """
    
    # Rescore path: User provided feedback on previous output
    if previous_output and user_prompt:
        message = await client.messages.create(
            model=MODEL_HAIKU,
            max_tokens=4096,
            messages=[{
                "role": "user",
                "content": build_rescore_prompt(
                    previous_output=previous_output,
                    user_prompt=user_prompt
                ),
            }],
        )
        text = message.content[0].text if message.content else "[]"
        match = _extract_json_array(text)
        if match:
            try:
                return json.loads(match)
            except Exception:
                pass
        return previous_output

    # Initial generation path
    location = input_data.get("location", {})
    city = location.get("city", "")
    budget = str(input_data.get("budget", "2"))
    interests = input_data.get("interests", [])
    dates = input_data.get("dates", {})
    start_date = dates.get("start", "")
    end_date = dates.get("end", "")
    days = input_data.get("daysNumber", 3)

    # Note: Each sub-agent returns a list[Attraction] based on its specific signature.
    fetcher_map = {
        "restaurants": lambda: fetch_restaurants(input_data),
        "nightlife":   lambda: fetch_nightlife(input_data),
        "history":     lambda: fetch_history(input_data),
        "sports":      lambda: fetch_sports(input_data),
        "extreme":     lambda: fetch_extreme(input_data),
        "treks":       lambda: fetch_treks(input_data),
        "beach":       lambda: fetch_beach(input_data),
        "spa":         lambda: fetch_spa(input_data),
        "events":      lambda: fetch_events(input_data),
        "shopping":    lambda: fetch_shopping(input_data)
    }

    # Fetch concurrently from all active sub-agents
    tasks = []
    for interest in interests:
        if interest in fetcher_map:
            tasks.append(fetcher_map[interest]())
        else:
            # Fallback to generic subagent for unknown interests
            tasks.append(fetch_generic(city, interest, budget))

    results = await asyncio.gather(*tasks, return_exceptions=True)

    raw: list[Attraction] = []
    for r in results:
        if not isinstance(r, Exception):
            raw.extend(r)

    if not raw:
        return []

    # Format the raw output with the LLM into the exact requested JSON layout
    message = await client.messages.create(
        model=MODEL_HAIKU,
        max_tokens=4096,
        messages=[{
            "role": "user",
            "content": build_attraction_prompt(
                input_data=input_data,
                raw_data=[a.to_dict() for a in raw],
            ),
        }],
    )

    text = message.content[0].text if message.content else "[]"
    match = _extract_json_array(text)
    if match:
        try:
            return json.loads(match)
        except Exception:
            pass
    return []

def _extract_json_array(text: str) -> Optional[str]:
    start = text.find("[")
    end = text.rfind("]")
    if start != -1 and end != -1:
        return text[start : end + 1]
    return None
