from utils.llm import async_client, MODEL_HAIKU

async def gather_beaches(location: str) -> str:
    """
    Sub-agent responsible for finding beaches around a given location.
    Returns a formatted string list of beaches to the calling agent.
    """
    
    system_prompt = (
        "You are the Beach Subagent. Your sole responsibility is to identify "
        "the best beaches near a given location. Provide a concise, bulleted list "
        "of beaches, including a 1-sentence highlight for each. "
        "Do not include conversational filler, just the list."
    )
    
    # Call Claude 3.5 Haiku via OpenRouter
    response = await async_client.messages.create(
        model=MODEL_HAIKU,
        max_tokens=1024,
        temperature=0.3, # Lower temperature for factual answers
        system=system_prompt,
        messages=[
            {
                "role": "user", 
                "content": f"Find the best beaches near: {location}"
            }
        ]
    )
    
    # Return the text generated by the LLM
    return response.content[0].text
